name: connector
registered_version: Connector-v0

ic_board:
    generation_type: online_random_seed # online_seq_rw, online_parallel_rw, online_random_seed, online_lsystems, offline
    board_name: bfs_base # replace with string from interface if using offline or none if using online
    grid_size: 10
    num_agents: 5

seed_extension:
    randomness: 0
    two_sided: true
    extension_iterations: 1
    extension_steps: 1e23

network:
    transformer_num_blocks: 4
    transformer_num_heads: 8
    transformer_key_size: 16
    transformer_mlp_units: [512]
    conv_n_channels: 32

training:
    num_epochs: 500
    num_learner_steps_per_epoch: 100
    n_steps: 20
    total_batch_size: 128

evaluation:
    eval_total_batch_size: 5000
    greedy_eval_total_batch_size: 5000

a2c:
    normalize_advantage: False
    discount_factor: 0.99
    bootstrapping_factor: 0.95
    l_pg: 1.0
    l_td: 1.0
    l_en: 0.01
    learning_rate: 2e-4
